[package]
name = "simparse-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "simparse"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
simparse-core = { path = "../simparse-core" }

[dev-dependencies]
tempfile.workspace = true
