[package]
name = "simparse-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
flate2.workspace = true
quick-xml.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
simparse-hdf5 = { path = "../simparse-hdf5" }
tar.workspace = true
thiserror.workspace = true
walkdir.workspace = true
zip.workspace = true

[dev-dependencies]
sha2 = "0.10"
tempfile.workspace = true
